version: "3.8"

services:
  geth:
    image: ethereum/client-go:stable
    container_name: geth
    ports:
      - "8545:8545"
      - "30303:30303"
    volumes:
      - ./geth_data:/root/.ethereum
      - ./genesis.json:/genesis.json
    command: >
      sh -c "
        geth init /genesis.json &&
        geth --networkid 51515 --http --http.addr 0.0.0.0 --http.port 8545 --http.api eth,net,web3,debug,personal --nodiscover --allow-insecure-unlock
      "
